# Generated by Django 4.1.4 on 2022-12-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mounts', '0002_alter_mountainpass_autumn_alter_mountainpass_spring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
                ('summer', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
                ('autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
                ('spring', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='mountainpass',
            name='autumn',
        ),
        migrations.RemoveField(
            model_name='mountainpass',
            name='spring',
        ),
        migrations.RemoveField(
            model_name='mountainpass',
            name='summer',
        ),
        migrations.RemoveField(
            model_name='mountainpass',
            name='winter',
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mounts.level'),
        ),
    ]
