# Generated by Django 4.1.4 on 2022-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mounts', '0004_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountainpass',
            name='level',
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='autumn',
            field=models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2),
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='spring',
            field=models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2),
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='summer',
            field=models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2),
        ),
        migrations.AddField(
            model_name='mountainpass',
            name='winter',
            field=models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
